# enable cxx11 using any version of CMake #
macro(use_cxx11)
	if(CMAKE_VERSION VERSION_LESS "3.1")
		if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")
		elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
		elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Qstd=c++11")
		elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
			
		endif()
	else()
		set(CMAKE_CXX_STANDARD 11)
	endif()
endmacro(use_cxx11)